# Site settings
title: Stamatis Platokoukis
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Stamatis Platokoukis
user_description: Adaptable Developer - Data Engineer from Greece, transitioning from Mechanical Engineering. Passionate about crafting innovative solutions. Embracing the
coding world with engineering expertise, driving progress through creativity and technical acumen
user_title: Software Engineer
email: stamplato@gmail.com
# twitter_username: lorem_ipsum
instagram_username: stamplato
facebook_username: platokoukis.stamatis
linkedin_username: stamatis-platokoukis
github_username:  stplato
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

