# Site settings
title: Stamatis Platokoukis
description: A personal portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: https://stplato.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Stamatis Platokoukis
user_description: 
user_title: MEng Mechanical Engineer/ Software Engineer
email: stamplato@gmail.com
# twitter_username: lorem_ipsum
instagram_username: stamplato
facebook_username: platokoukis.stamatis
linkedin_username: stamatis-platokoukis
github_username:  stplato
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

